[2023-07-08T18:38:08.700+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_python.build_and_run_containers manual__2023-07-05T03:56:32.740955+00:00 [queued]>
[2023-07-08T18:38:08.715+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_python.build_and_run_containers manual__2023-07-05T03:56:32.740955+00:00 [queued]>
[2023-07-08T18:38:08.716+0200] {taskinstance.py:1308} INFO - Starting attempt 17 of 18
[2023-07-08T18:38:08.743+0200] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): build_and_run_containers> on 2023-07-05 03:56:32.740955+00:00
[2023-07-08T18:38:08.764+0200] {standard_task_runner.py:57} INFO - Started process 584011 to run task
[2023-07-08T18:38:08.830+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'execute_python', 'build_and_run_containers', 'manual__2023-07-05T03:56:32.740955+00:00', '--job-id', '801', '--raw', '--subdir', 'DAGS_FOLDER/thesis_container.py', '--cfg-path', '/tmp/tmp8lv9rc9r']
[2023-07-08T18:38:08.855+0200] {standard_task_runner.py:85} INFO - Job 801: Subtask build_and_run_containers
[2023-07-08T18:38:09.122+0200] {task_command.py:410} INFO - Running <TaskInstance: execute_python.build_and_run_containers manual__2023-07-05T03:56:32.740955+00:00 [running]> on host DESKTOP-3KJU1M7.
[2023-07-08T18:38:09.596+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='execute_python' AIRFLOW_CTX_TASK_ID='build_and_run_containers' AIRFLOW_CTX_EXECUTION_DATE='2023-07-05T03:56:32.740955+00:00' AIRFLOW_CTX_TRY_NUMBER='17' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-05T03:56:32.740955+00:00'
[2023-07-08T18:44:36.077+0200] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 584011. PIDs of all processes in the group: [584012, 584013, 584026, 584123, 584011]
[2023-07-08T18:44:36.310+0200] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 584011
[2023-07-08T18:44:36.452+0200] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-07-08T18:44:36.731+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=584012, status='terminated', started='18:38:09') (584012) terminated with exit code None
[2023-07-08T18:44:37.672+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/reynel1995/airflow/dags/thesis_container.py", line 162, in build_and_run_containers
    subprocess.run(build_command, shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1144, in communicate
    self.wait()
  File "/usr/lib/python3.10/subprocess.py", line 1207, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1941, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.10/subprocess.py", line 1899, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-07-08T18:44:53.999+0200] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_python, task_id=build_and_run_containers, execution_date=20230705T035632, start_date=20230708T163808, end_date=20230708T164453
[2023-07-08T18:44:54.334+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 801 for task build_and_run_containers (Task received SIGTERM signal; 584011)
[2023-07-08T18:44:55.196+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=584011, status='terminated', exitcode=1, started='18:38:08') (584011) terminated with exit code 1
